apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090   # Grafana inside compose talks to Prometheus by container name
    isDefault: true
    editable: false
