global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'quizify-backend'
    metrics_path: /metrics
    static_configs:
      - targets: ['backend:3001']        # docker-compose service name and container port

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
